/** Current app-shell product surface semantics for Development Intelligence. */
export const APP_SHELL_SURFACE_DEVELOPMENT_INTELLIGENCE = [
  {
    developmentIntelligence: {
      kind: 'surface', id: 'desk', label: 'Desk', role: 'zone',
      relationships: [
        { kind: 'exposes', to: 'action:desk.create-set' },
        { kind: 'exposes', to: 'action:desk.delete-set' },
        { kind: 'exposes', to: 'action:desk.duplicate-set' },
        { kind: 'exposes', to: 'action:desk.export-set' },
        { kind: 'exposes', to: 'action:desk.generate-set' },
        { kind: 'exposes', to: 'action:desk.manage-location' },
        { kind: 'exposes', to: 'action:desk.open-set' },
        { kind: 'exposes', to: 'action:desk.pin-set' },
        { kind: 'exposes', to: 'action:desk.rename-set' },
        { kind: 'exposes', to: 'action:desk.save-move-set' },
        { kind: 'exposes', to: 'action:desk.send-pipeline' },
        { kind: 'exposes', to: 'capability:card-rendering.spatial-gestures' },
        { kind: 'exposes', to: 'capability:creator.exact-context-return' },
        { kind: 'exposes', to: 'capability:desk.adaptive-artifact-density' },
        { kind: 'exposes', to: 'capability:desk.bounded-spatial-workspace' },
        { kind: 'exposes', to: 'capability:desk.context-restoration' },
        { kind: 'exposes', to: 'capability:desk.fit-custom-camera' },
        { kind: 'exposes', to: 'capability:desk.multi-artifact-spatial-move' },
        { kind: 'exposes', to: 'capability:desk.readable-fit-floor' },
        { kind: 'exposes', to: 'capability:desk.reflective-set-organization' },
      ],
    },
  },
  {
    developmentIntelligence: {
      kind: 'surface', id: 'library', label: 'Library', role: 'zone',
      relationships: [
        { kind: 'exposes', to: 'action:library.close-locations' },
        { kind: 'exposes', to: 'action:library.close-tool' },
        { kind: 'exposes', to: 'action:library.continue' },
        { kind: 'exposes', to: 'action:library.copy-published-template' },
        { kind: 'exposes', to: 'action:library.delete-copy' },
        { kind: 'exposes', to: 'action:library.duplicate' },
        { kind: 'exposes', to: 'action:library.edit-pipeline' },
        { kind: 'exposes', to: 'action:library.manage-location' },
        { kind: 'exposes', to: 'action:library.open' },
        { kind: 'exposes', to: 'action:library.refresh' },
        { kind: 'exposes', to: 'action:library.retire-pipeline' },
        { kind: 'exposes', to: 'action:library.save-move' },
        { kind: 'exposes', to: 'action:library.send-pipeline' },
        { kind: 'exposes', to: 'action:library.test-pipeline' },
        { kind: 'exposes', to: 'action:library.use-published' },
        { kind: 'exposes', to: 'action:library.view-source' },
        { kind: 'exposes', to: 'action:library.withdraw-pipeline' },
      ],
    },
  },
  {
    developmentIntelligence: {
      kind: 'surface', id: 'profile', label: 'Profile', role: 'zone',
      relationships: [
        { kind: 'exposes', to: 'action:profile.close-utility' },
        { kind: 'exposes', to: 'action:profile.manage-account' },
      ],
    },
  },
  {
    developmentIntelligence: {
      kind: 'surface', id: 'public', label: 'Public', role: 'public',
      relationships: [
        { kind: 'exposes', to: 'route:/' },
        { kind: 'exposes', to: 'route:/about' },
        { kind: 'exposes', to: 'route:/accessibility' },
        { kind: 'exposes', to: 'route:/cameron' },
        { kind: 'exposes', to: 'route:/contact' },
        { kind: 'exposes', to: 'route:/contributor-terms' },
        { kind: 'exposes', to: 'route:/contributors' },
        { kind: 'exposes', to: 'route:/creator-pass-terms' },
        { kind: 'exposes', to: 'route:/mcp-card-set-preview' },
        { kind: 'exposes', to: 'route:/mcp-template-preview' },
        { kind: 'exposes', to: 'route:/plans' },
        { kind: 'exposes', to: 'route:/privacy' },
        { kind: 'exposes', to: 'route:/refund' },
        { kind: 'exposes', to: 'route:/roadmap' },
        { kind: 'exposes', to: 'route:/sign-in/[[...sign-in]]' },
        { kind: 'exposes', to: 'route:/sign-up/[[...sign-up]]' },
        { kind: 'exposes', to: 'route:/supporter-terms' },
        { kind: 'exposes', to: 'route:/terms' },
      ],
    },
  },
] as const;
