/**
 * elementKits.tsx
 *
 * Insertable element seeds for the template editor element rail.
 * These are local editor tools, not developer-pipeline assets.
 */

import type { ElementType } from 'react';
import {
  Badge,
  BoxSelect,
  Crown,
  Frame,
  Gem,
  Image as ImageIcon,
  LineChart,
  MinusIcon,
  Sparkles,
  Square,
  Type,
} from 'lucide-react';
import type { FreeformCardElement } from '@/types';





// ─── Element Kits ─────────────────────────────────────────────────────────────

export const elementKits: Array<{
  label: string;
  description: string;
  category: 'Core' | 'Premium Parts' | 'Element Recipes' | 'Ornaments';
  icon: ElementType;
  type: FreeformCardElement['type'];
  preset?: Partial<FreeformCardElement>;
}> = [
  { label: 'Free Text', description: 'Plain dynamic or static text layer.', category: 'Core', icon: Type, type: 'text' },
  { label: 'Artwork', description: 'Image slot linked to a data key or URL.', category: 'Core', icon: ImageIcon, type: 'image' },
  { label: 'Rune Icon', description: 'A scalable symbol with stroke and fill controls.', category: 'Core', icon: Sparkles, type: 'icon' },
  { label: 'Shape', description: 'Basic rectangle, ellipse, or line foundation.', category: 'Core', icon: Square, type: 'shape' },
  {
    label: 'Cost Orb',
    description: 'Circular cost counter designed for top-right card costs.',
    category: 'Element Recipes',
    icon: Badge,
    type: 'text',
    preset: {
      name: 'Cost Badge',
      content: '{{cost:"3"}}',
      width: 64,
      height: 64,
      fontSize: 'text-2xl',
      fontWeight: 'font-bold',
      textAlign: 'center',
      backgroundColor: '#1b1410',
      textColor: '#f5d27b',
      borderColor: '#d5ad54',
      borderWidth: 'border-2',
      borderRadius: 'rounded-full',
    },
  },
  {
    label: 'Art Window',
    description: 'Gold-lined ornamental frame for artwork regions.',
    category: 'Element Recipes',
    icon: Frame,
    type: 'shape',
    preset: {
      name: 'Art Frame',
      width: 502,
      height: 338,
      backgroundColor: 'rgba(0,0,0,0.12)',
      fillColor: 'rgba(0,0,0,0.12)',
      borderColor: '#d5ad54',
      strokeColor: '#d5ad54',
      strokeWidth: 2,
      borderRadius: 'rounded-md',
    },
  },
  {
    label: 'Parchment',
    description: 'Readable fantasy text panel for rules or flavor copy.',
    category: 'Element Recipes',
    icon: LineChart,
    type: 'text',
    preset: {
      name: 'Rules Text',
      content: '{{rulesText:"Flying\\nWhen this enters play, draw a card."}}',
      width: 500,
      height: 170,
      fontSize: 'text-sm',
      fontWeight: 'font-normal',
      textAlign: 'left',
      backgroundColor: 'rgba(246,232,199,0.82)',
      textColor: '#21180d',
      borderColor: '#b58b35',
      borderWidth: 'border',
      borderRadius: 'rounded-md',
    },
  },
  {
    label: 'Gold Rule',
    description: 'Ornamental metallic divider for type lines and footer breaks.',
    category: 'Ornaments',
    icon: MinusIcon,
    type: 'shape',
    preset: {
      name: 'Gilded Divider',
      shapeKind: 'rectangle',
      width: 460,
      height: 14,
      fillColor: '#d5ad54',
      strokeColor: '#d5ad54',
      strokeWidth: 0,
      borderWidth: '_none_',
      borderRadius: 'rounded-full',
      backgroundImageUrl: 'linear-gradient(90deg, transparent 0%, #7f5d1f 8%, #f5d27b 18%, #7f5d1f 28%, transparent 36%, #d5ad54 50%, transparent 64%, #7f5d1f 72%, #f5d27b 82%, #7f5d1f 92%, transparent 100%)',
    },
  },
  {
    label: 'Rune Chain',
    description: 'A row of arcane game symbols for rarity, factions, or schools.',
    category: 'Ornaments',
    icon: Sparkles,
    type: 'text',
    preset: {
      name: 'Rune Chain',
      content: '✦  ◆  ✧  ◆  ✦',
      width: 310,
      height: 32,
      fontSize: 'text-lg',
      fontWeight: 'font-bold',
      textAlign: 'center',
      backgroundColor: 'rgba(13,17,23,0.7)',
      backgroundImageUrl: 'linear-gradient(90deg, transparent, rgba(122,82,204,0.5), rgba(213,173,84,0.35), transparent)',
      textColor: '#f5d27b',
      borderColor: '#7a52cc',
      borderWidth: 'border',
      borderRadius: 'rounded-full',
    },
  },
  {
    label: 'Ornate Text Box',
    description: 'Premium rules/flavor frame with darker fan-card styling.',
    category: 'Element Recipes',
    icon: BoxSelect,
    type: 'text',
    preset: {
      name: 'Ornate Text Box',
      content: '{{rulesText:"When this enters play, forge a relic.\\n\\nFlavor text lives here."}}',
      width: 500,
      height: 190,
      fontSize: 'text-sm',
      fontWeight: 'font-normal',
      textAlign: 'left',
      padding: 'p-3',
      backgroundColor: '#15100b',
      backgroundImageUrl: 'linear-gradient(180deg, rgba(213,173,84,0.22), rgba(0,0,0,0.18)), radial-gradient(circle at 50% 0%, rgba(122,82,204,0.22), transparent 48%)',
      textColor: '#f7e6b0',
      borderColor: '#d5ad54',
      borderWidth: 'border-4',
      borderRadius: 'rounded-lg',
    },
  },
  {
    label: 'Stat Orb',
    description: 'Power/toughness or rating counter for card corners.',
    category: 'Element Recipes',
    icon: Crown,
    type: 'text',
    preset: {
      name: 'Stat Gem',
      content: '{{power:"2"}}',
      width: 58,
      height: 58,
      fontSize: 'text-xl',
      fontWeight: 'font-bold',
      textAlign: 'center',
      backgroundColor: '#19130e',
      textColor: '#f5d27b',
      borderColor: '#d5ad54',
      borderWidth: 'border-2',
      borderRadius: 'rounded-full',
    },
  },
  {
    label: 'Title Plate',
    description: 'Dark-gold title banner with fantasy border styling.',
    category: 'Element Recipes',
    icon: Badge,
    type: 'text',
    preset: {
      name: 'Title Plate',
      content: '{{cardName:"EMBERCLAW WHELP"}}',
      width: 420,
      height: 42,
      fontSize: 'text-lg',
      fontWeight: 'font-bold',
      textAlign: 'center',
      backgroundColor: '#17100b',
      textColor: '#f7df9d',
      borderColor: '#d5ad54',
      borderWidth: 'border-2',
      borderRadius: 'rounded-md',
    },
  },
  {
    label: 'Type Plate',
    description: 'Creature, spell, equipment, or quest type-line strip.',
    category: 'Element Recipes',
    icon: LineChart,
    type: 'text',
    preset: {
      name: 'Type Plate',
      content: '{{typeLine:"CREATURE - DRAGON"}}',
      width: 500,
      height: 34,
      fontSize: 'text-xs',
      fontWeight: 'font-semibold',
      textAlign: 'left',
      backgroundColor: '#21170d',
      textColor: '#f6dfaa',
      borderColor: '#d5ad54',
      borderWidth: 'border',
      borderRadius: 'rounded-sm',
    },
  },
  {
    label: 'Corner Sigil',
    description: 'Small rune accent for ornate card corners and frames.',
    category: 'Ornaments',
    icon: Gem,
    type: 'icon',
    preset: {
      name: 'Corner Sigil',
      iconName: 'Gem',
      width: 36,
      height: 36,
      strokeColor: '#d5ad54',
      fillColor: '#17100b',
      backgroundColor: '#17100b',
      borderColor: '#d5ad54',
      borderWidth: 'border',
      borderRadius: 'rounded-full',
    },
  },
  {
    label: 'Foil Veil',
    description: 'Subtle purple-gold overlay for premium card finishes.',
    category: 'Ornaments',
    icon: Sparkles,
    type: 'shape',
    preset: {
      name: 'Foil Veil',
      width: 520,
      height: 780,
      backgroundColor: 'rgba(122,82,204,0.16)',
      fillColor: 'rgba(122,82,204,0.16)',
      backgroundImageUrl: 'linear-gradient(135deg, rgba(122,82,204,0.18), rgba(213,173,84,0.14) 48%, rgba(255,255,255,0.08))',
      borderWidth: '_none_',
      borderRadius: 'rounded-xl',
      opacity: 0.45,
    },
  },
];

export const CONSOLIDATED_ELEMENT_KITS: typeof elementKits = [
  { label: 'Text', description: 'Static or placeholder-driven text.', category: 'Core', icon: Type, type: 'text' },
  { label: 'Image', description: 'Artwork, uploaded image, or data-key image slot.', category: 'Core', icon: ImageIcon, type: 'image' },
  { label: 'Icon', description: 'Lucide, TCG symbol, or uploaded custom icon.', category: 'Core', icon: Sparkles, type: 'icon' },
  { label: 'Shape', description: 'Rectangle or ellipse primitive for badges and masks.', category: 'Core', icon: Square, type: 'shape' },
  {
    label: 'Divider / Rule',
    description: 'A line element for section breaks, separators, and ornamental dividers.',
    category: 'Core',
    icon: MinusIcon,
    type: 'shape',
    preset: { name: 'Divider', shapeKind: 'line', shapeRole: 'divider', width: 470, height: 36, strokeWidth: 0, borderWidth: '_none_', borderRadius: 'rounded-none', appearance: { dividerAsset: '/card-assets/dividers/gilded-filigree.svg', assetKind: 'divider', shapeRole: 'divider', textureOpacity: 100, material: { baseColor: 'transparent', texture: { kind: 'none' } }, border: { kind: 'none', width: 0, radius: 0 } } },
  },
];
