import type { TCGCardTemplate } from '@/types';

export const PREDEFINED_FRAME_VISUAL_PROPERTIES: Record<string, Partial<TCGCardTemplate>> = {
  'classic-gold': {
    baseBackgroundColor: '#fDF4D8',
    baseTextColor: '#4A3B2A',
    cardBorderRadius: '0.75rem',
    cardBorderColor: 'transparent',
    cardBorderWidth: '6px',
    cardBorderStyle: 'solid',
    cardBackgroundImageUrl: undefined,
    frameStyle: 'classic-gold',
    cardBorderImageSource: 'CSS: Classic Gold Gradient',
  },
  'minimal-dark': {
    baseBackgroundColor: '#282828',
    baseTextColor: '#c0c0c0',
    cardBorderColor: '#4a4a4a',
    cardBorderWidth: '2px',
    cardBorderStyle: 'solid',
    cardBorderRadius: '0.25rem',
    cardBackgroundImageUrl: undefined,
    frameStyle: 'minimal-dark',
    cardBorderImageSource: undefined,
  },
  'arcane-purple': {
    baseBackgroundColor: '#4A0E7E',
    baseTextColor: '#E6E6FA',
    cardBorderColor: '#D8BFD8',
    cardBorderWidth: '5px',
    cardBorderStyle: 'solid',
    cardBorderRadius: '0.6rem',
    cardBackgroundImageUrl: undefined,
    frameStyle: 'arcane-purple',
    cardBorderImageSource: undefined,
  },
  standard: {
    baseBackgroundColor: '#FFFFFF',
    baseTextColor: '#000000',
    cardBorderRadius: '0.5rem',
    cardBorderColor: undefined,
    cardBorderWidth: '4px',
    cardBorderStyle: 'solid',
    cardBackgroundImageUrl: undefined,
    frameStyle: 'standard',
    cardBorderImageSource: undefined,
  },
  custom: {
    baseBackgroundColor: '',
    baseTextColor: '',
    cardBorderRadius: '0.5rem',
    cardBorderColor: '',
    cardBorderWidth: '4px',
    cardBorderStyle: 'solid',
    cardBackgroundImageUrl: undefined,
    frameStyle: 'custom',
    cardBorderImageSource: undefined,
  },
};
